CREATE TABLE `article_category` (
	`id`	BIGINT	AUTO_INCREMENT COMMENT '아이디' PRIMARY KEY,
	`name`	VARCHAR(20)	NOT NULL	COMMENT '이름'
) COMMENT '게시글 카테고리' CHARSET = utf8mb4;

CREATE TABLE `article` (
	`id`	BIGINT AUTO_INCREMENT	NOT NULL	COMMENT '아이디' PRIMARY KEY,
	`article_category_id`	BIGINT	NOT NULL	COMMENT '카테고리 아이디',
	`title`	VARCHAR(45)	NOT NULL	COMMENT '제목',
	`content`	TINYTEXT	NOT NULL	COMMENT '내용',
	`left_item`	VARCHAR(100)	NOT NULL	COMMENT '왼쪽항목',
	`right_item`	VARCHAR(100)	NOT NULL	COMMENT '오른쪽항목',
	`left_count`	BIGINT	NOT NULL	COMMENT '왼쪽항목 득표수',
	`right_count`	BIGINT	NOT NULL	COMMENT '오른쪽항목 득표수',
	`total_count`	BIGINT	NOT NULL	COMMENT '전체 득표수',
	`password`	VARCHAR(8)	NOT NULL	COMMENT '비밀번호',
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP() NOT NULL	COMMENT '등록일자',
	`modified_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP() NOT NULL	COMMENT '수정일자',
    CONSTRAINT `FK_ARTICLE_ARTICLE_CATEGORY_ID` FOREIGN KEY (`article_category_id`) REFERENCES `article_category` (`id`)
) COMMENT '게시글' CHARSET = utf8mb4;

CREATE TABLE `article_comment` (
	`id` BIGINT	NOT NULL AUTO_INCREMENT	COMMENT '아이디' PRIMARY KEY, 
	`article_id` BIGINT NOT NULL COMMENT '게시판 아이디',
	`password`	VARCHAR(8)	NOT NULL	COMMENT '비밀번호',
	`content`	TINYTEXT	NOT NULL	COMMENT '내용',
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP() NOT NULL	COMMENT '등록일자',
	`modified_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP() NOT NULL	COMMENT '수정일자',
	CONSTRAINT `FK_ARTICLE_COMMENT_ARTICLE_ID` FOREIGN KEY (`article_id`) REFERENCES `article` (`id`) 
) COMMENT '게시글 댓글' CHARSET = utf8mb4;

CREATE TABLE `vote_history` (
	`id`	BIGINT	AUTO_INCREMENT NOT NULL COMMENT '아이디' PRIMARY KEY,
  `article_id`	BIGINT	NOT NULL	COMMENT '게시글 아이디',
	`user_id`	VARCHAR(300)	NOT NULL	COMMENT '유저 아이디',
	`created_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP() NOT NULL	COMMENT '등록일자',
	`modified_at`	DATETIME	DEFAULT CURRENT_TIMESTAMP() NOT NULL	COMMENT '수정일자',
	CONSTRAINT `FK_VOTE_HISTORY_ARTICLE_ID` FOREIGN KEY (`article_id`) REFERENCES `article` (`id`) 
) COMMENT '투표 참여 이력' CHARSET = utf8mb4;